
# This file is for local development with Supabase CLI
# Learn more at: https://supabase.com/docs/reference/cli/config

project_id = "mxgocqawpsrfsmgskugn"

[api]
port = 54321
schemas = ["storage", "public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[storage]

[realtime]

[functions]
[functions.serve]
port = 54330

[[functions.http]]
name = "suggest-price"
verify_jwt = true

[[functions.http]]
name = "assign-seller-role"
verify_jwt = true
