// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxgocqawpsrfsmgskugn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Z29jcWF3cHNyZnNtZ3NrdWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4Mzc3NDUsImV4cCI6MjA1NjQxMzc0NX0.3nKJjhjhQ-k_4hpcdfpAF1EJhRYc7QZUCJya455ZMeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);